image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
  - port: 6650

tasks:
  - init: sudo mv apache-pulsar-2.5.0 /workspace/cms/pulsar
  command: /workspace/cms/pulsar/bin/pulsar standalone

  
vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.7.8:oixMSF1r3cXQPfOQ34+sTA==